language: r
r:
  - 3.2
  - 3.3
  - devel
  
os:
  - linux
  - osx

matrix:
  exclude:
  - r: 3.3
    os: osx
  - r: devel
    os: osx
  allow_failures:
  - r: devel
    os: linux

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'